### ISSUE TITLE
Doesn't work

### ISSUE THREAD

**Issue by nzminecraftDOTcom** [Zerthick/NoExp#1]
Attempted to disable ores from dropping XP due to some bug with Veinminer and Spongeforge conflicting down the line
Didn't disable XP drops from ores, server did two full restarts and while the config was set to false, it failed to do it's job.
Spongeforge version spongeforge-1.12.2-2705-7.1.0-BETA-3151

**Comment by Zerthick** [comment]
Odd, I'll look into this

**Comment by yamy19** [comment]
Any Idea when we can get an update on weather there will be a hotfix for this not working on the current spongforge?

**Comment by Zerthick** [comment]
Right now https://github.com/Zerthick/NoExp/releases/tag/v1.0.2 😄

**Comment by nzminecraftDOTcom** [comment]
Sweeeeet will update this asap :D
